import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Generated Website',
  description: 'A website generated by Avallon',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}